name: ✅ Task Template
description: Template for individual subtasks (1.1.1 Core Schema Migration, etc.)
title: "[TASK] "
labels: ["task"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## Task Overview
        Use this template for individual subtasks within epics.
        
  - type: input
    id: task-id
    attributes:
      label: Task ID
      description: Task identifier (e.g., 1.1.1, 2.2.3)
      placeholder: "1.1.1"
    validations:
      required: true
      
  - type: input
    id: task-name
    attributes:
      label: Task Name
      description: Descriptive name for this task
      placeholder: "Core Schema Migration"
    validations:
      required: true
      
  - type: input
    id: parent-epic
    attributes:
      label: Parent Epic
      description: Which epic does this task belong to?
      placeholder: "1.1 Database Architecture"
    validations:
      required: true
      
  - type: input
    id: augment-uuid
    attributes:
      label: Augment Task UUID
      description: UUID from Augment's task management system
      placeholder: "mcU5SAgTENu5TX3abHVjZE"
    validations:
      required: false
      
  - type: textarea
    id: task-description
    attributes:
      label: Task Description
      description: Detailed description of what this task involves
      placeholder: "Convert Prisma schemas (User, Project, Link, Domain) to Laravel migrations with proper relationships"
    validations:
      required: true
      
  - type: input
    id: estimated-time
    attributes:
      label: Estimated Time
      description: Expected time to complete this task
      placeholder: "3-4 days"
    validations:
      required: true
      
  - type: dropdown
    id: task-type
    attributes:
      label: Task Type
      description: Type of work this task represents
      options:
        - Development
        - Research
        - Documentation
        - Testing
        - Review
        - Deployment
        - Configuration
    validations:
      required: true
      
  - type: dropdown
    id: component-area
    attributes:
      label: Component Area
      description: Which area of the system does this task affect?
      options:
        - Backend - Database
        - Backend - API
        - Backend - Authentication
        - Backend - Jobs
        - Backend - Analytics
        - Backend - Billing
        - Frontend - Components
        - Frontend - Pages
        - Frontend - Authentication
        - Frontend - Admin
        - Frontend - Partner
        - Testing - Unit
        - Testing - Integration
        - Testing - E2E
        - Infrastructure
        - Documentation
    validations:
      required: true
      
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: Specific criteria that must be met for this task to be considered complete
      placeholder: |
        - [ ] User migration creates users table with proper columns
        - [ ] Project migration creates projects table with foreign keys
        - [ ] Link migration includes all necessary indexes
        - [ ] Domain migration supports custom domain functionality
        - [ ] All migrations have proper rollback methods
      render: markdown
    validations:
      required: true
      
  - type: textarea
    id: implementation-details
    attributes:
      label: Implementation Details
      description: Specific implementation requirements or technical details
      placeholder: |
        **Database Tables to Create:**
        - users (id, name, email, email_verified_at, password, timestamps)
        - projects (id, name, slug, user_id, timestamps)
        - links (id, domain, key, url, project_id, timestamps)
        - domains (id, slug, verified, project_id, timestamps)
        
        **Key Relationships:**
        - User hasMany Projects
        - Project hasMany Links
        - Project hasMany Domains
      render: markdown
      
  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies
      description: What needs to be completed before this task can start?
      placeholder: "List any dependencies on other tasks or external factors"
      
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: Priority level for this task
      options:
        - Critical
        - High
        - Medium
        - Low
    validations:
      required: true
      
  - type: textarea
    id: dub-reference
    attributes:
      label: Dub-Main Reference Links
      description: Specific dub-main files or components this task references
      placeholder: |
        **Reference Files:**
        - `/Users/yasinboelhouwer/shorts/dub-main/packages/prisma/schema/user.prisma`
        - `/Users/yasinboelhouwer/shorts/dub-main/packages/prisma/schema/project.prisma`
        - `/Users/yasinboelhouwer/shorts/dub-main/packages/prisma/schema/link.prisma`
        
        **Key Patterns to Follow:**
        - Schema structure and field types
        - Relationship definitions
        - Index configurations
        
  - type: textarea
    id: testing-checklist
    attributes:
      label: Testing Checklist
      description: Testing requirements for this task
      placeholder: |
        - [ ] Migration runs successfully
        - [ ] Migration rollback works correctly
        - [ ] All relationships are properly defined
        - [ ] Indexes are created as expected
        - [ ] Foreign key constraints work properly
      render: markdown
      
  - type: textarea
    id: additional-notes
    attributes:
      label: Additional Notes
      description: Any additional information, considerations, or context
      placeholder: "Additional context, gotchas, or considerations for this task"
